project_id = "rlsontubfdpqzhoqezks"

[functions.create-guest-session]
verify_jwt = false

[functions.match-opposite]
verify_jwt = false

[functions.validate-session]
verify_jwt = false

[functions.send-message]
verify_jwt = false

[functions.get-room-data]
verify_jwt = false

[functions.end-chat]
verify_jwt = false

[functions.block-user]
verify_jwt = false