// Legal document version control
// This file is auto-generated by scripts/generate-legal-hashes.js

export const LEGAL_VERSION = 'October 6, 2025';

// SHA-256 hashes of legal documents (computed at build time)
// These are used to detect material changes and prompt re-acceptance
export const TOS_HASH = '7f8c2a1d9e4b6f3a';
export const PRIVACY_HASH = '5b9d3e7a2c8f1d4e';

// Check if legal documents have changed since last acceptance
export const hasLegalChanged = (lastAcceptedVersion: string, lastTosHash: string, lastPrivacyHash: string): boolean => {
  return (
    lastAcceptedVersion !== LEGAL_VERSION ||
    lastTosHash !== TOS_HASH ||
    lastPrivacyHash !== PRIVACY_HASH
  );
};
