// Legal document version control
// This file is auto-generated by scripts/generate-legal-hashes.js

export const LEGAL_VERSION = '2025-10-06';

// SHA-256 hashes of legal documents (computed at build time)
// These are used to detect material changes and prompt re-acceptance
export const TOS_HASH = 'pending-build'; // Will be computed by pre-build script
export const PRIVACY_HASH = 'pending-build'; // Will be computed by pre-build script

// Check if legal documents have changed since last acceptance
export const hasLegalChanged = (lastAcceptedVersion: string, lastTosHash: string, lastPrivacyHash: string): boolean => {
  return (
    lastAcceptedVersion !== LEGAL_VERSION ||
    lastTosHash !== TOS_HASH ||
    lastPrivacyHash !== PRIVACY_HASH
  );
};
