export const ICEBREAKER_PROMPTS = [
  "What's a small joy from your day today?",
  "What's a hobby you enjoy when you have a free hour?",
  "What's a song you never skip when it comes on?",
  "What's a comfort show or movie you rewatch?",
  "What's a go-to snack you never get tired of?",
  "What's a place you find relaxing (anywhere, big or small)?",
  "What's something you learned recently that stuck with you?",
  "What kind of mornings do you prefer: slow or jump-right-in?",
  "What's a smell that instantly takes you back somewhere?",
  "What's your favorite way to take a walk (music, podcast, silence)?",
  "What's a book or article you enjoyed lately?",
  "What's a tiny life upgrade you recommend?",
  "What's your ideal weekend morning?",
  "What's a skill you'd love to get better at just for fun?",
  "What's your favorite season and why?",
  "What's a game you like—video, board, or mobile?",
  "What's a meal you could eat once a week and be happy?",
  "What's your preferred way to organize your day?",
  "What's a childhood pastime you still enjoy?",
  "What's a favorite sound (rain, pages turning, distant trains, etc.)?",
  "What's a small ritual that makes your day feel \"set\"?",
  "What's your favorite kind of dessert?",
  "What's a creative outlet you return to?",
  "What's a helpful tip someone gave you that you still use?",
  "What's a favorite way to unwind after work/school?",
  "What's a memory that always makes you smile?",
  "What's a movie genre you'll always give a chance?",
  "What's a household product or app you recommend to everyone?",
  "What's a go-to way you like to learn something new?",
  "What's a favorite type of weather to experience?",
  "What's a small goal you're working on right now?",
  "What's a simple recipe you enjoy making?",
  "What's a favorite type of puzzle or brainteaser?",
  "What's a tiny habit that improved your day-to-day?",
  "What's your favorite beverage ritual (coffee, tea, soda, water)?",
  "What's a piece of media you loved more than you expected?",
  "What's your preferred pace of life lately: calm or busy?",
  "What's a favorite view—city lights, forests, coastline, skylines?",
  "What's an item you always carry that's surprisingly useful?",
  "What's a favorite way to celebrate small wins?",
  "What's a comfort activity when you need a reset?",
  "What's a museum, park, or public place you enjoy?",
  "What's a form of art you like to experience (any kind)?",
  "What's a scent you'd put in a candle?",
  "What's a small act of kindness you noticed recently?",
  "What's a playlist theme you'd make right now?",
  "What's your favorite kind of breakfast?",
  "What's a simple pleasure you look forward to each week?",
  "What's a tool or gadget that genuinely saves you time?",
  "What's something you like to notice when you're people-watching (fashion, dogs, architecture, etc.)?",
];

export const getRandomPrompt = (): string => {
  return ICEBREAKER_PROMPTS[Math.floor(Math.random() * ICEBREAKER_PROMPTS.length)];
};
